# permissions to do edit gitops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops-editor-role
rules:
- apiGroups:
  - gitops.kazylla.jp
  resources:
  - gitops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitops.kazylla.jp
  resources:
  - gitops/status
  verbs:
  - get
  - patch
  - update
